# Generated by Django 6.0 on 2025-12-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_medicalrecord_patient_user_labresult_medication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(),
        ),
    ]
