# Generated by Django 6.0.1 on 2026-01-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_patient_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='case_no',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
