# Generated by Django 6.0.1 on 2026-01-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_patient_case_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
